# Generated by Django 6.0.6 on 2026-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_usado', models.CharField(default='qr', max_length=20)),
                ('resultado', models.CharField(choices=[('permitido', 'Permitido'), ('denegado', 'Denegado')], max_length=20)),
                ('motivo_denegado', models.CharField(blank=True, choices=[('membresia_vencida', 'Membresía Vencida'), ('sin_membresia', 'Sin Membresía'), ('clases_agotadas', 'Clases Agotadas'), ('suspendido', 'Suspendido')], max_length=30, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accesos',
            },
        ),
        migrations.CreateModel(
            name='MetodoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('qr', 'Código QR'), ('huella', 'Huella Digital'), ('rfid', 'Tarjeta RFID/NFC'), ('manual', 'Manual')], default='qr', max_length=20)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metodos_acceso',
            },
        ),
    ]
