# Generated by Django 6.0.6 on 2026-06-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accesos', '0001_initial'),
        ('gyms', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='socios.membresia'),
        ),
        migrations.AddField(
            model_name='acceso',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='socios.socio'),
        ),
        migrations.AddField(
            model_name='acceso',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='gyms.sucursal'),
        ),
        migrations.AddField(
            model_name='metodoacceso',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_acceso', to='socios.socio'),
        ),
        migrations.AddIndex(
            model_name='acceso',
            index=models.Index(fields=['timestamp'], name='accesos_timesta_d1cc66_idx'),
        ),
        migrations.AddIndex(
            model_name='acceso',
            index=models.Index(fields=['socio', 'timestamp'], name='accesos_socio_i_e26c10_idx'),
        ),
        migrations.AddIndex(
            model_name='acceso',
            index=models.Index(fields=['sucursal', 'timestamp'], name='accesos_sucursa_11cc28_idx'),
        ),
    ]
