# Generated by Django 6.0.6 on 2026-08-11 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='motivo_denegado',
            field=models.CharField(blank=True, choices=[('membresia_vencida', 'Membresía Vencida'), ('sin_membresia', 'Sin Membresía'), ('clases_agotadas', 'Clases Agotadas'), ('suspendido', 'Suspendido'), ('otra_sucursal', 'Pertenece a Otra Sucursal')], max_length=30, null=True),
        ),
    ]
