# Generated by Django 6.0.6 on 2026-08-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_acceso_autorizado_por_alter_acceso_motivo_denegado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='motivo_denegado',
            field=models.CharField(blank=True, choices=[('membresia_vencida', 'Membresía Vencida'), ('sin_membresia', 'Sin Membresía'), ('clases_agotadas', 'Clases Agotadas'), ('suspendido', 'Suspendido'), ('otra_sucursal', 'Pertenece a Otra Sucursal'), ('ya_registrado', 'Ya Registró su Acceso Hoy')], max_length=30, null=True),
        ),
    ]
