# Generated by Django 6.0.6 on 2026-08-11 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anterior', models.DateField(blank=True, null=True)),
                ('fecha_nueva', models.DateField(blank=True, null=True)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_autorizados', to=settings.AUTH_USER_MODEL)),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='socios.membresia')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ajustes_membresia',
                'ordering': ['-creado_en'],
            },
        ),
    ]
