# Generated by Django 6.0.6 on 2026-08-11 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_gym_politica_visitantes'),
        ('socios', '0003_ajustemembresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socios', to='gyms.sucursal'),
        ),
    ]
