# Generated by Django 6.0.6 on 2026-08-11 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_clase_sucursal_equipamiento_sucursal'),
        ('socios', '0005_backfill_sucursal_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='gyms.sucursal'),
        ),
    ]
