# Generated by Django 6.0.6 on 2026-08-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_gasto_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='anonimizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='tutor_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='socio',
            name='tutor_parentesco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='socio',
            name='tutor_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
