# Generated by Django 6.0.6 on 2026-08-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_alter_gym_politica_visitantes'),
        ('socios', '0007_socio_anonimizado_en_socio_tutor_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='numero_socio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='socio',
            constraint=models.UniqueConstraint(fields=('gym', 'numero_socio'), name='numero_socio_unico_por_gym'),
        ),
    ]
