# Generated by Django 6.0.6 on 2026-08-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_alter_gym_politica_visitantes'),
        ('socios', '0009_backfill_numero_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioPlanSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_sucursal', to='socios.plan')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_plan', to='gyms.sucursal')),
            ],
            options={
                'db_table': 'precios_plan_sucursal',
                'unique_together': {('plan', 'sucursal')},
            },
        ),
    ]
