# Generated by Django 6.0.6 on 2026-08-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0011_socio_eliminado_en_socio_eliminado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
    ]
