# Generated by Django 6.0.6 on 2026-08-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0012_gasto_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='es_visita',
            field=models.BooleanField(default=False),
        ),
    ]
