# Generated by Django 6.0.6 on 2026-08-20 19:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0005_gym_direccion_gym_horario'),
        ('socios', '0007_socio_anonimizado_en_socio_tutor_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aviso_privacidad', 'Aviso de Privacidad (gym → socios)'), ('terminos_servicio', 'Términos y Condiciones del software (proveedor → gym)'), ('convenio_encargado', 'Convenio de Encargado del tratamiento')], max_length=30)),
                ('version', models.CharField(help_text='Etiqueta visible para el usuario, p. ej. "1.0" o "2026-08".', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(help_text='Texto del documento en Markdown.')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_legales', to='gyms.gym')),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documentos_legales',
                'ordering': ['-vigente_desde', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otorgado_por', models.CharField(choices=[('socio', 'El propio socio'), ('tutor', 'Padre, madre o tutor (socio menor de edad)')], default='socio', max_length=10)),
                ('medio', models.CharField(choices=[('mostrador', 'Aceptado en mostrador ante recepción'), ('digital', 'Aceptado por el socio en línea')], default='mostrador', max_length=15)),
                ('tutor_nombre', models.CharField(blank=True, max_length=200)),
                ('tutor_parentesco', models.CharField(blank=True, max_length=50)),
                ('aceptado_en', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('capturado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_capturados', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='socios.socio')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='legal.documentolegal')),
            ],
            options={
                'db_table': 'consentimientos_socio',
                'ordering': ['-aceptado_en'],
            },
        ),
        migrations.CreateModel(
            name='AceptacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado_en', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones_legales', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceptaciones', to='legal.documentolegal')),
            ],
            options={
                'db_table': 'aceptaciones_usuario',
                'ordering': ['-aceptado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentolegal',
            constraint=models.UniqueConstraint(fields=('gym', 'tipo', 'version'), name='documento_version_unica'),
        ),
        migrations.AddConstraint(
            model_name='aceptacionusuario',
            constraint=models.UniqueConstraint(fields=('usuario', 'documento'), name='aceptacion_usuario_unica'),
        ),
    ]
