# Generated by Django 6.0.6 on 2026-07-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0002_clase_equipamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pago_vencido', 'Pago Vencido'), ('inventario', 'Inventario'), ('membresia_por_vencer', 'Membresía por Vencer'), ('socio_nuevo', 'Socio Nuevo'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('mensaje', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gyms.gym')),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
