# Generated by Django 6.0.6 on 2026-07-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='archivada',
            field=models.BooleanField(default=False),
        ),
    ]
