# Generated by Django 6.0.7 on 2026-08-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_clase_sucursal_equipamiento_sucursal'),
        ('usuarios', '0003_backfill_sucursal_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='horario_semanal',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sucursales_permitidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_permitidos', to='gyms.sucursal'),
        ),
    ]
