# Generated by Django 6.0.6 on 2026-07-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('resistencia', 'Resistencia'), ('fisico', 'Físico'), ('combinaciones', 'Combinaciones'), ('defensa', 'Defensa'), ('sparring', 'Sparring')], max_length=20)),
                ('profesor', models.CharField(max_length=150)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dias', models.CharField(max_length=100)),
                ('cupo_max', models.PositiveIntegerField(default=20)),
                ('inscritos', models.PositiveIntegerField(default=0)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('todos', 'Todos')], default='todos', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='gyms.gym')),
            ],
            options={
                'db_table': 'clases',
            },
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('impacto', 'Impacto'), ('infraestructura', 'Infraestructura'), ('proteccion', 'Protección'), ('cardio', 'Cardio'), ('piso', 'Piso'), ('pesas', 'Pesas')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('ultima_revision', models.DateField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamientos', to='gyms.gym')),
            ],
            options={
                'db_table': 'equipamiento',
            },
        ),
    ]
