# Generated by Django 6.0.6 on 2026-08-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_clase_equipamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='politica_visitantes',
            field=models.CharField(choices=[('libre', 'Puede entrar a cualquier sucursal'), ('autorizacion', 'Requiere autorización del dueño'), ('bloqueado', 'Solo su sucursal')], default='libre', help_text='Qué hacer si un socio se presenta en una sucursal distinta a la suya', max_length=20),
        ),
    ]
