# Generated by Django 6.0.6 on 2026-08-11 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_gym_politica_visitantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='gyms.sucursal'),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamientos', to='gyms.sucursal'),
        ),
    ]
