# Generated by Django 6.0.6 on 2026-08-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_clase_sucursal_equipamiento_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='horario',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
