# Generated by Django 6.0.6 on 2026-08-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_gym_direccion_gym_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='politica_visitantes',
            field=models.CharField(choices=[('libre', 'Puede entrar a cualquier sucursal'), ('autorizacion', 'Recepción decide caso por caso'), ('bloqueado', 'Solo su sucursal')], default='libre', help_text='Qué hacer si un socio se presenta en una sucursal distinta a la suya', max_length=20),
        ),
    ]
